### ISSUE TITLE
Requesting code with handling segmentation image

### ISSUE THREAD

**Issue by yellowjs0304** [airsplay/R2R-EnvDrop#13]
Hello, Thank u for sharing your great work.
I downloaded your segmentation images which is divided into 36 pieces.

I want to check these into panoramic image.
Is there any code with attaching 36 pieces to one panoramic image?

Could you please share code?
Thank you.

**Comment by airsplay** [comment]
I do not have a stitching code in hand but I could provide the code that I generate these views.

The code to generate these segmentations is modified from the matterport3D repo. I am not an expert in Graphics thus I hack the code for rendering these images.

The code is here:
https://drive.google.com/file/d/1XghR5ymJGzIFvV5t1cOQwTR_HkBz6Lzo/view

The main hacked function is mpview::GLUTRedraw. I also modified many other parts to make it possible.

**Comment by yellowjs0304** [comment]
Thank u and sorry... I saw your reply too late
