### ISSUE TITLE
Help, error about the code

### ISSUE THREAD

**Issue by jingquanliang** [airsplay/R2R-EnvDrop#15]
hi, when i run the code with the following instruction: bash run/agent.py , i got the following error,  i dont konw why, please  help me about that! thank u

Traceback (most recent call last):
  File "r2r_src/train.py", line 470, in <module>
    train_val()
  File "r2r_src/train.py", line 386, in train_val
    train(train_env, tok, args.iters, val_envs=val_envs)
  File "r2r_src/train.py", line 132, in train
    listner.train(interval, feedback=feedback_method)   # Train interval iters
  File "/home/jing/selfmonitoring-agent/r2r_src/agent.py", line 820, in train
    self.loss.backward()
  File "/home/jing/anaconda2/envs/python3.6/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jing/anaconda2/envs/python3.6/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Invalid index in scatterAdd at /opt/conda/conda-bld/pytorch_1579022051443/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:721

**Comment by airsplay** [comment]
The error seems to say the same thing as "out-of-index", which does not appear before in this proj.
Could you specify the running environment (e.g., Pytorch version, CUDA version, OS system)?

**Comment by jingquanliang** [comment]
> The error seems to say the same thing as "out-of-index", which does not appear before in this proj.
> Could you specify the running environment (e.g., Pytorch version, CUDA version, OS system)?

yes， the enviroment is below:
   Pytorch version: python3.6
   OS system : Ubuntu 18.04
   CUDA version:  No Cuda, just on cpu for learning the code

**Comment by jingquanliang** [comment]
> > The error seems to say the same thing as "out-of-index", which does not appear before in this proj.
> > Could you specify the running environment (e.g., Pytorch version, CUDA version, OS system)?
> 
> yes， the enviroment is below:
> python version: python3.6
> Pytorch version: 1.4.0
> OS system : Ubuntu 18.04
> CUDA version: No Cuda, just on cpu for learning the code

 when i use the following enviroment , it also occurs the error , and i really dont know why?
python version: python3.6
pytorch version: 1.2.0
OS system: Ubuntu 16.04
CUDA version: No Cuda, just on cpu for learning the code
===========================
the error is  below:
![image](https://user-images.githubusercontent.com/8544622/74095511-defd2e00-4b2c-11ea-9668-68dedcd24c68.png)

**Comment by jingquanliang** [comment]
> > > The error seems to say the same thing as "out-of-index", which does not appear before in this proj.
> > > Could you specify the running environment (e.g., Pytorch version, CUDA version, OS system)?
> > 
> > 
> > yes， the enviroment is below:
> > python version: python3.6
> > Pytorch version: 1.4.0
> > OS system : Ubuntu 18.04
> > CUDA version: No Cuda, just on cpu for learning the code
> > =====================================
> > when i use the following enviroment , it also occurs the error , and i really dont know why?
> > python version: python3.6
> > pytorch version: 1.4.0
> > OS system: Ubuntu 16.04
> > CUDA version: cuda 9.2
> > ===========================
> > the error is  below:
> > ![image](https://user-images.githubusercontent.com/8544622/74095511-defd2e00-4b2c-11ea-9668-68dedcd24c68.png)

when i use another gpu, the problem sovled, thanks!
