### ISSUE TITLE
One possiable bug in agent._teacher_action()

### ISSUE THREAD

**Issue by ZuoJiaxing** [airsplay/R2R-EnvDrop#19]
One possible bug here:
https://github.com/airsplay/R2R-EnvDrop/blob/1f460912e0b522de5d0a21181efd194f90386a77/r2r_src/agent.py#L184

**Comment by airsplay** [comment]
Thanks. Could you specify it a little bit more?

**Comment by airsplay** [comment]
Close the issue because no specification is given (only an `else` statement is marked and I did not find unusual behavior around this statement).

**Comment by ZuoJiaxing** [comment]
Please look into the code, the above can be linked to the bug I reported. It seems that else is matched with for??? 

                for k, candidate in enumerate(ob['candidate']):
                    if candidate['viewpointId'] == ob['teacher']:   # Next view point
                        a[i] = k
                        break
                else:   # Stop here
                    assert ob['teacher'] == ob['viewpoint']         # The teacher action should be "STAY HERE"
                    a[i] = len(ob['candidate'])

**Comment by ZuoJiaxing** [comment]
I'm sorry that there no bug here. It's my misunderstanding. Thanks!
