### ISSUE TITLE
Paper Question

### ISSUE THREAD

**Issue by AmingWu** [airsplay/R2R-EnvDrop#2]
Hey,

When I run  bash run/speaker.bash 0,  there is an error.

run/speaker.bash: line 6: unbuffer: command not found

**Comment by airsplay** [comment]
Hi,

I remove the "unbuffer" command which tries to reduce the delay in showing results. Please go and try it!

The long reason for using "unbuffer" here:
I used os command "tee" to allow logging in file.  However, "tee" overwrites the os buffer size thus the printed results would be delayed. "Unbuffer" generally creates a "virtual buffer" to eliminate this problem.
