### ISSUE TITLE
Beam Search setting

### ISSUE THREAD

**Issue by qweas120** [airsplay/R2R-EnvDrop#22]
Hi @airsplay , I have a question about the Beam Search setting.

In Sec 5 of your EnvDrop paper, it mentioned that "**_beam search is usable when the environment is explored and saved in the agent’s memory but the agent does not have enough computational capacity to fine-tune its navigational model._**". 

Does it mean that the model used in beam-search was not fine-tuned in test unseen environments? And did previous works fine-tune in test unseen set for Beam Search setting?

Thanks.

**Comment by airsplay** [comment]
Yes, the agent is only trained with train envs but do search on the test env (which is not applicable in real life if the test env is not scanned and provided).  To the best of my knowledge,  I am not aware of any previous work that utilizes unseen-env exploration in their paper, but it would be best to verify with their original papers.

**Comment by qweas120** [comment]
Indeed. Thanks for the response.
