### ISSUE TITLE
How to run with multiple gpus?

### ISSUE THREAD

**Issue by yellowjs0304** [airsplay/R2R-EnvDrop#24]
Hi, Thank u for sharing nice work.

I followed your script, but i can't train this in multiple gpus.

I used  "bash run/bt_envdrop.bash 0, 3", but it cannot equally divided into two GPUs.

Could you please tell me how to do it?

**Comment by airsplay** [comment]
Did not support multiple GPU yet TAT...

**Comment by yellowjs0304** [comment]
Thank you for quick response.
