### ISSUE TITLE
Picking the best checkpoint in the pre-exploration setting.

### ISSUE THREAD

**Issue by zwx8981** [airsplay/R2R-EnvDrop#25]
Hi, how did you select the checkpoint for test in the pre-explpration setting ? Did you still pick the checkpoint according to the performances on the validation-unseen set?

**Comment by airsplay** [comment]
Yea, according to the single-run validation-unseen result only. 

But I think that it is allowed to use the validation-unseen to pick the best checkpoint as long as the results on test environments are shown.

**Comment by zwx8981** [comment]
@airsplay Thanks for the reply.
