### ISSUE TITLE
Difference between aug_paths and Speaker-Follower (Literal) Paths?

### ISSUE THREAD

**Issue by siddk** [airsplay/R2R-EnvDrop#28]
The "augmented" paths in the download file (http://www.cs.unc.edu/~airsplay/aug_paths.json) do not seem to be the "ground truth" paths from the original Speaker-Follower paper (http://people.eecs.berkeley.edu/~ronghang/projects/speaker_follower/data_augmentation/R2R_literal_speaker_data_augmentation_paths.json).

Is there a difference? If so, what is it?

**Comment by airsplay** [comment]
The augmented paths of Speaker-follower are not released when this project is developed. We thus collected these augmented paths on our own following the setup in their paper.

The paths are always the shortest paths from the beginning to the end thus the intermediate viewpoints are not logged.

**Comment by siddk** [comment]
Understood - thanks so much!
