### ISSUE TITLE
About angle feature size

### ISSUE THREAD

**Issue by qweas120** [airsplay/R2R-EnvDrop#7]
Hi @airsplay , I note that the angle feature size is 4 in both the paper and the default parameter setting but 128 in `run\agent.bash`. 
Is this a special design? :)

**Comment by airsplay** [comment]
Hi, @qweas120 .

We follow the original implementation of panoramic view (speaker-follower) in doing this. Although the [paper](https://arxiv.org/pdf/1806.02724.pdf) takes a 4-dimensional vector for simplicity
```
... a 4-dimensional orientation feature [sin ψ; cos ψ; sin θ; cos θ]...
```
, the [code](https://github.com/ronghanghu/speaker_follower/blob/33da6cdc62f447776cf0e3fc595f57fd536bbfe5/tasks/R2R/env.py#L87) uses an 128-dim embedding:
```
    embedding = np.zeros((len(adj_loc_list), feature_dim + 128), np.float32)
```

It was a solution to balance the energy of two features (i.e., ResNet features and positional features) by repeating the smaller one. 

By the way, in our [EMNLP 2019 paper](https://arxiv.org/pdf/1908.07490.pdf), we used Layer_Normalization to address the imbalanced energy of ResNet feature and positional feature. Please kindly check Eqn 1 in Sec 2.1.  We have not tested the LayerNorm technique on VLN thus I am not sure whether it is also applicable here.

**Comment by qweas120** [comment]
@airsplay Wonderful reply. Thanks.
